#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# TODO
# Look at VLAN stats https://devcentral.f5.com/questions/snmp-vlan-statistics
# - F5-BIGIP-SYSTEM-MIB::sysVlanxStat
# - seems VLANs are present in the ifxtable. They are picked up by the if64 native check
# Trunk stats
# - F5-BIGIP-SYSTEM-MIB::sysTrunk
# - F5-BIGIP-SYSTEM-MIB::sysTrunkStat
# remove looseversion requirement http://lists.mathias-kettner.de/pipermail/checkmk-en/2013-January/008361.html


# .1.3.6.1.4.1.3375.2.1.2.4.5.3.1.1   index for ifname
# .1.3.6.1.4.1.3375.2.1.2.4.1.2.1.17  index for ifstate
# .1.3.6.1.4.1.3375.2.1.2.4.5.3.1.10  index for IN bytes
# .1.3.6.1.4.1.3375.2.1.2.4.5.3.1.6   index for OUT bytes

f5_bigip_interface_states = {
    1 : "down (has no link and is initialized)",
    2 : "disabled (has been forced down)",
    3 : "uninitialized (has not been initialized)",
    4 : "loopback (in loopback mode)",
    5 : "unpopulated (interface not physically populated)",
}


def check_f5_bigip_interfaces(item, params, info):
    #import pprint; pprint.pprint(info)
    for port, ifstate, inbytes, outbytes in info:
        if item != port:
            continue

        if int(ifstate) != 0:
            return (2, "State of %s is %s" %
                    (f5_bigip_interface_states.get(ifstate, "unhandled (%d)" % ifstate), port))

        this_time = int(time.time())

        # get_rate does not exist in OMD 1.20
        #in_per_sec  = get_rate("f5_interface.in.%s" % item,  this_time, saveint(inbytes))
        #out_per_sec  = get_rate("f5_interface.out.%s" % item,  this_time, saveint(outbytes))
        in_timedif,  in_per_sec  = get_counter("f5.interface.in.%s" % item,  this_time, saveint(inbytes))
        out_timedif,  out_per_sec  = get_counter("f5_interface.out.%s" % item,  this_time, saveint(outbytes))

        inbytes_h = get_bytes_human_readable(in_per_sec)
        outbytes_h = get_bytes_human_readable(out_per_sec)
        perf = [
            ("bytes_in", in_per_sec),
            ("bytes_out", out_per_sec),
        ]
        return (0, "in bytes: %s/s, out bytes: %s/s" % (inbytes_h, outbytes_h), perf)
    return 3, "Interface not found in SNMP data"


from distutils.version import LooseVersion

# !!! Bug in LTM 11.5.1 for 2000/4000 platforms
# https://support.f5.com/kb/en-us/solutions/public/16000/000/sol16064.html

# Behavior change from 11.2.0 and onwards
# IF-MIB::ifHCInOctets has been replaced with F5-BIGIP-SYSTEM-MIB::sysIfxStatHCInOctets
# IF-MIB::ifHCOutOctets has been replaced with F5-BIGIP-SYSTEM-MIB::sysIfxStatHCOutOctets
#
# https://support.f5.com/kb/en-us/solutions/public/14000/400/sol14473.html
#
# NOTE : ifHCInOctets is present on version 11.5.4 (at least on platform bigip5250)

check_info["f5_bigip_interfaces"] = {
    "check_function"        : check_f5_bigip_interfaces,
    "inventory_function"    : lambda info: [ (x[0], {'state': 0 } ) for x in info if (int(x[1]) == 0 and x[0])],
    "service_description"   : "f5 Interface %s",
    "has_perfdata"          : True,
    "snmp_scan_function"    : lambda oid: '.1.3.6.1.4.1.3375.2' in oid(".1.3.6.1.2.1.1.2.0") and "big-ip" in oid(".1.3.6.1.4.1.3375.2.1.4.1.0").lower() and LooseVersion(oid(".1.3.6.1.4.1.3375.2.1.4.2.0")) >= LooseVersion("11.2.0"),
    "snmp_info"             : ( ".1.3.6.1.4.1.3375.2.1.2.4", ["5.3.1.1", "1.2.1.17", "5.3.1.10", "5.3.1.6"]),
}
